name: Create Nuget package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-pack:
    name: Build and Pack
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Packaging
        run: dotnet pack

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: ./nupkg/*.nupkg
          generate_release_notes: true







